export const colors = [
  { name: "Indian Red", hex_code: "#CD5C5C" },
  { name: "Light Coral", hex_code: "#F08080" },
  { name: "Salmon", hex_code: "#FA8072" },
  { name: "Dark Salmon", hex_code: "#E9967A" },
  { name: "Light Salmon", hex_code: "#FFA07A" },
  { name: "Crimson", hex_code: "#DC143C" },
  { name: "Red", hex_code: "#FF0000" },
  { name: "Fire Brick", hex_code: "#B22222" },
  { name: "Dark Red", hex_code: "#8B0000" },
  { name: "Pink", hex_code: "#FFC0CB" },
  { name: "Light Pink", hex_code: "#FFB6C1" },
  { name: "Hot Pink", hex_code: "#FF69B4" },
  { name: "Deep Pink", hex_code: "#FF1493" },
  { name: "Medium Violet Red", hex_code: "#C71585" },
  { name: "Pale Violet Red", hex_code: "#DB7093" },
  { name: "Coral", hex_code: "#FF7F50" },
  { name: "Tomato", hex_code: "#FF6347" },
  { name: "Orange Red", hex_code: "#FF4500" },
  { name: "Dark Orange", hex_code: "#FF8C00" },
  { name: "Orange", hex_code: "#FFA500" },
  { name: "Gold", hex_code: "#FFD700" },
  { name: "Yellow", hex_code: "#FFFF00" },
  { name: "Light Yellow", hex_code: "#FFFFE0" },
  { name: "Lemon Chiffon", hex_code: "#FFFACD" },
  { name: "Light Goldenrod Yellow", hex_code: "#FAFAD2" },
  { name: "Papaya Whip", hex_code: "#FFEFD5" },
  { name: "Moccasin", hex_code: "#FFE4B5" },
  { name: "Peach Puff", hex_code: "#FFDAB9" },
  { name: "Pale Goldenrod", hex_code: "#EEE8AA" },
  { name: "Khaki", hex_code: "#F0E68C" },
  { name: "Dark Khaki", hex_code: "#BDB76B" },
  { name: "Lavender", hex_code: "#E6E6FA" },
  { name: "Thistle", hex_code: "#D8BFD8" },
  { name: "Plum", hex_code: "#DDA0DD" },
  { name: "Violet", hex_code: "#EE82EE" },
  { name: "Orchid", hex_code: "#DA70D6" },
  { name: "Fuchsia", hex_code: "#FF00FF" },
  { name: "Magenta", hex_code: "#FF00FF" },
  { name: "Medium Orchid", hex_code: "#BA55D3" },
  { name: "Medium Purple", hex_code: "#9370DB" },
  { name: "Blue Violet", hex_code: "#8A2BE2" },
  { name: "Dark Violet", hex_code: "#9400D3" },
  { name: "Dark Orchid", hex_code: "#9932CC" },
  { name: "Dark Magenta", hex_code: "#8B008B" },
  { name: "Purple", hex_code: "#800080" },
  { name: "Indigo", hex_code: "#4B0082" },
  { name: "Slate Blue", hex_code: "#6A5ACD" },
  { name: "Cornsilk", hex_code: "#FFF8DC" },
  { name: "Blanched Almond", hex_code: "#FFEBCD" },
  { name: "Bisque", hex_code: "#FFE4C4" },
  { name: "Navajo White", hex_code: "#FFDEAD" },
  { name: "Wheat", hex_code: "#F5DEB3" },
  { name: "Burly Wood", hex_code: "#DEB887" },
  { name: "Tan", hex_code: "#D2B48C" },
  { name: "Rosy Brown", hex_code: "#BC8F8F" },
  { name: "Sandy Brown", hex_code: "#F4A460" },
  { name: "Goldenrod", hex_code: "#DAA520" },
  { name: "Dark Golden Rod", hex_code: "#B8860B" },
  { name: "Peru", hex_code: "#CD853F" },
  { name: "Chocolate", hex_code: "#D2691E" },
  { name: "Saddle Brown", hex_code: "#8B4513" },
  { name: "Sienna", hex_code: "#A0522D" },
  { name: "Brown", hex_code: "#A52A2A" },
  { name: "Maroon", hex_code: "#800000" },
  { name: "Aqua", hex_code: "#00FFFF" },
  { name: "Cyan", hex_code: "#00FFFF" },
  { name: "Light Cyan", hex_code: "#E0FFFF" },
  { name: "Pale Turquoise", hex_code: "#AFEEEE" },
  { name: "Aquamarine", hex_code: "#7FFFD4" },
  { name: "Turquoise", hex_code: "#40E0D0" },
  { name: "Medium Turquoise", hex_code: "#48D1CC" },
  { name: "Dark Turquoise", hex_code: "#00CED1" },
  { name: "Cadet Blue", hex_code: "#5F9EA0" },
  { name: "Steel Blue", hex_code: "#4682B4" },
  { name: "Light Steel Blue", hex_code: "#B0C4DE" },
  { name: "Powder Blue", hex_code: "#B0E0E6" },
  { name: "Light Blue", hex_code: "#ADD8E6" },
  { name: "Sky Blue", hex_code: "#87CEEB" },
  { name: "Light Sky Blue", hex_code: "#87CEFA" },
  { name: "Deep Sky Blue", hex_code: "#00BFFF" },
  { name: "Dodger Blue", hex_code: "#1E90FF" },
  { name: "Cornflower Blue", hex_code: "#6495ED" },
  { name: "Medium Slate Blue", hex_code: "#7B68EE" },
  { name: "Royal Blue", hex_code: "#4169E1" },
  { name: "Blue", hex_code: "#0000FF" },
  { name: "Medium Blue", hex_code: "#0000CD" },
  { name: "Dark Blue", hex_code: "#00008B" },
  { name: "Navy", hex_code: "#000080" },
  { name: "Midnight Blue", hex_code: "#191970" },
  { name: "Green Yellow", hex_code: "#ADFF2F" },
  { name: "Chartreuse", hex_code: "#7FFF00" },
  { name: "Lawn Green", hex_code: "#7CFC00" },
  { name: "Lime", hex_code: "#00FF00" },
  { name: "Lime Green", hex_code: "#32CD32" },
  { name: "Pale Green", hex_code: "#98FB98" },
  { name: "Light Green", hex_code: "#90EE90" },
  { name: "Medium Spring Green", hex_code: "#00FA9A" },
  { name: "Spring Green", hex_code: "#00FF7F" },
  { name: "Medium Sea Green", hex_code: "#3CB371" },
  { name: "Sea Green", hex_code: "#2E8B57" },
  { name: "Forest Green", hex_code: "#228B22" },
  { name: "Green", hex_code: "#008000" },
  { name: "Dark Green", hex_code: "#006400" },
  { name: "Yellow Green", hex_code: "#9ACD32" },
  { name: "Olive Drab", hex_code: "#6B8E23" },
  { name: "Olive", hex_code: "#808000" },
  { name: "Dark Olive Green", hex_code: "#556B2F" },
  { name: "Medium Aquamarine", hex_code: "#66CDAA" },
  { name: "Dark Sea Green", hex_code: "#8FBC8F" },
  { name: "Light Sea Green", hex_code: "#20B2AA" },
  { name: "Dark Cyan", hex_code: "#008B8B" },
  { name: "Teal", hex_code: "#008080" },
  { name: "White", hex_code: "#FFFFFF" },
  { name: "Snow", hex_code: "#FFFAFA" },
  { name: "Honey Dew", hex_code: "#F0FFF0" },
  { name: "Mint Cream", hex_code: "#F5FFFA" },
  { name: "Azure", hex_code: "#F0FFFF" },
  { name: "Alice Blue", hex_code: "#F0F8FF" },
  { name: "Ghost White", hex_code: "#F8F8FF" },
  { name: "White Smoke", hex_code: "#F5F5F5" },
  { name: "Seashell", hex_code: "#FFF5EE" },
  { name: "Beige", hex_code: "#F5F5DC" },
  { name: "Old Lace", hex_code: "#FDF5E6" },
  { name: "Floral White", hex_code: "#FFFAF0" },
  { name: "Ivory", hex_code: "#FFFFF0" },
  { name: "Antique White", hex_code: "#FAEBD7" },
  { name: "Linen", hex_code: "#FAF0E6" },
  { name: "Lavender Blush", hex_code: "#FFF0F5" },
  { name: "Misty Rose", hex_code: "#FFE4E1" },
  { name: "Gainsboro", hex_code: "#DCDCDC" },
  { name: "Light Gray", hex_code: "#D3D3D3" },
  { name: "Silver", hex_code: "#C0C0C0" },
  { name: "Dark Gray", hex_code: "#A9A9A9" },
  { name: "Gray", hex_code: "#808080" },
  { name: "Dim Gray", hex_code: "#696969" },
  { name: "Light Slate Gray", hex_code: "#778899" },
  { name: "Slate Gray", hex_code: "#708090" },
  { name: "Dark Slate Gray", hex_code: "#2F4F4F" },
  { name: "Black", hex_code: "#000000" },
];
