name: ci

on:
  push:
    branches:
      - "main"
      - "dev"
      - "pub"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push main branch
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:latest
      - name: Build and push dev branch
        if: github.ref_name == 'dev'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:dev
      - name: Build and push pub branch
        if: github.ref_name == 'pub'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:pub
      - name: Alert
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Full Name: ${{ github.event.workflow_run.head_commit.author.name }}
            Username: ${{ github.actor }}
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            Status: ${{ job.status }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
